# Generated by Django 6.0.2 on 2026-02-22 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code promotionnel unique (ex: MOVE25, COVOITURAGE)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom lisible de la promotion (ex: Covoiturage -25%)', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée de la promotion')),
                ('promo_type', models.CharField(choices=[('covoiturage', 'Covoiturage (-25%)'), ('bagages', 'Bagages (-10%)'), ('loyal_client', 'Client Fidèle'), ('referral', 'Parrainage'), ('seasonal', 'Saisonnière'), ('first_time', 'Premier Trajet'), ('cashback', 'Cashback MOVECoin')], default='seasonal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('paused', 'Suspendu'), ('expired', 'Expiré'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', help_text='Type de réduction: pourcentage ou montant fixe', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Valeur de la réduction (% ou montant)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Réduction maximale en MOVECoin (optionnel)', max_digits=10, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum pour appliquer la promo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de début de la promotion')),
                ('end_date', models.DateTimeField(blank=True, help_text='Date de fin de la promotion (null = sans limite)', null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text="Nombre maximum d'utilisations (null = illimité)", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_uses_per_user', models.IntegerField(default=1, help_text="Nombre maximum d'utilisations par utilisateur", validators=[django.core.validators.MinValueValidator(1)])),
                ('usage_count', models.IntegerField(default=0, help_text="Nombre d'utilisations actuelles")),
                ('target_users', models.CharField(choices=[('all', 'Tous les utilisateurs'), ('new', 'Nouveaux utilisateurs'), ('loyal', 'Clients fidèles'), ('vip', 'Utilisateurs VIP')], default='all', max_length=50)),
                ('applicable_to_covoiturage', models.BooleanField(default=True, help_text="La promo s'applique-t-elle au covoiturage?")),
                ('applicable_to_bagages', models.BooleanField(default=True, help_text="La promo s'applique-t-elle aux bagages?")),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de MOVECoin retourné (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.IntegerField(default=0, help_text="Priorité d'affichage (plus élevé = plus important)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(help_text='Admin qui a créé cette promo', max_length=100)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['code', 'status'], name='promotions__code_24681a_idx'), models.Index(fields=['created_at'], name='promotions__created_dcd10a_idx'), models.Index(fields=['status'], name='promotions__status_b908b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_id', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Utilisation Promotion',
                'verbose_name_plural': 'Utilisations Promotions',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user_id', 'used_at'], name='promotions__user_id_fdb67c_idx'), models.Index(fields=['promotion', 'used_at'], name='promotions__promoti_7c7e67_idx')],
            },
        ),
    ]
