# Generated by Django 6.0.2 on 2026-02-22 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Adresse complète', max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude GPS', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude GPS', max_digits=9)),
                ('landmark', models.CharField(blank=True, help_text='Point de repère (optionnel)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='commande_lo_latitud_533952_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique (auto-générée)', max_length=50, unique=True)),
                ('user_id', models.CharField(db_index=True, help_text='ID du client qui a commandé', max_length=100)),
                ('driver_id', models.CharField(blank=True, db_index=True, help_text='ID du chauffeur assigné', max_length=100, null=True)),
                ('estimated_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance estimée en km', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance réelle en km', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_time', models.IntegerField(blank=True, help_text='Temps estimé en minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_time', models.IntegerField(blank=True, help_text='Temps réel en minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_type', models.CharField(choices=[('taxi', '🚕 Taxi'), ('moto', '🏍️ Moto'), ('scooter', '🛵 Scooter'), ('van', '🚐 Van'), ('vip', '👑 VIP'), ('corbillard', '⚰️ Corbillard'), ('tricycle', '🛺 Tricycle'), ('pickup', '🚘 Pickup')], default='taxi', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, help_text="Plaque d'immatriculation", max_length=50, null=True)),
                ('is_covoiturage', models.BooleanField(default=False, help_text='Client partage le trajet?')),
                ('is_bagages', models.BooleanField(default=False, help_text='Supplément bagages?')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Tarif de base en XAF', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('covoiturage_discount', models.DecimalField(decimal_places=2, default=0, help_text='Réduction covoiturage', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bagages_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Surcharge bagages', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('promotion_discount', models.DecimalField(decimal_places=2, default=0, help_text='Réduction promotion appliquée', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, help_text='Pourboire client', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Montant total en XAF', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('movecoin', 'MOVECoin'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('credit_card', 'Carte Bancaire'), ('cash', 'Espèces')], default='movecoin', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant payé', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('movecoin_earned', models.DecimalField(decimal_places=2, default=0, help_text='MOVECoin gagné par client', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('driver_movecoin_earned', models.DecimalField(decimal_places=2, default=0, help_text='MOVECoin gagné par chauffeur', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'En attente ⏳'), ('confirmed', 'Confirmée ✓'), ('accepted', 'Acceptée par chauffeur 👨\u200d💼'), ('driver_arriving', 'Chauffeur en approche 🚗'), ('driver_arrived', 'Chauffeur arrivé 📍'), ('in_progress', 'En cours 🚙'), ('completed', 'Complétée ✓'), ('cancelled_user', 'Annulée (utilisateur) ✗'), ('cancelled_driver', 'Annulée (chauffeur) ✗'), ('cancelled_admin', 'Annulée (admin) ✗'), ('no_show', 'Non présenté (no-show) 🚫')], db_index=True, default='pending', max_length=20)),
                ('user_notes', models.TextField(blank=True, help_text='Notes spéciales du client')),
                ('driver_notes', models.TextField(blank=True, help_text='Notes du chauffeur')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes administrateur')),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Heure de commande planifiée', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, help_text='Note du client (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_review', models.TextField(blank=True, help_text='Avis du client')),
                ('driver_rating', models.IntegerField(blank=True, help_text='Note du chauffeur (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_review', models.TextField(blank=True, help_text='Avis du chauffeur')),
                ('dropoff_location', models.ForeignKey(help_text="Point d'arrivée", on_delete=django.db.models.deletion.PROTECT, related_name='dropoffs', to='commande.location')),
                ('pickup_location', models.ForeignKey(help_text='Point de départ', on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='commande.location')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('client_review', models.TextField(blank=True)),
                ('client_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('driver_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_review', models.TextField(blank=True)),
                ('driver_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='commande.order')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(help_text="Qui a effectué le changement (user_id, driver_id, ou 'system')", max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Raison du changement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='commande.order')),
            ],
            options={
                'verbose_name': 'Historique Statut',
                'verbose_name_plural': 'Historiques Statut',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', '-created_at'], name='commande_or_user_id_0cbced_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver_id', '-created_at'], name='commande_or_driver__e7a4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='commande_or_status_9a6bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='commande_or_payment_d5bc31_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='commande_or_created_3cd642_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', '-created_at'], name='commande_or_order_i_3188fe_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['created_at'], name='commande_or_created_f4e236_idx'),
        ),
    ]
